### PR TITLE
examples of multiple windows

### LINKED ISSUE #17: build example of including multiple .ui in mainwindow.ui

### PR DESCRIPTION
**Pull request by prjemian**
- close #17

Main window (built from a ui file) adds additional content from another ui file.  Application uses the menu bar and provides an `About ...` dialog (modeless). 

The About box has two pushbuttons that launch a web browser to show a specific URL.  A third pushbutton brings up a new dialog showing the full text of the software license.

### CODE REVIEW

**Comment by prjemian** [comment]
Code from these two projects were used here:

- https://github.com/prjemian/pvMail
- https://github.com/prjemian/assign_gup

**Comment by prjemian** [comment]
image

image

image

**Comment by prjemian** [comment]
I will add a handling of preferences/configuration/settings to this branch.

**Review by rodolakis — APPROVED** [review]
LGTM

**Comment by prjemian** [comment]
Ok.  I'll make a new branch with my additions/changes.

**Pull request merged**
